import numpy as np

words = np.array([
    "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew",
    "kiwi", "lemon", "mango", "nectarine", "orange", "papaya", "quince", "raspberry", 
    "apple", "banana", "orange", "grape", "kiwi", "strawberry", "blueberry", "mango", "peach", "cherry",
    "pineapple", "melon", "watermelon", "papaya", "lemon", "lime", "apricot", "plum", "pear", "fig",
    "coconut", "raspberry", "blackberry", "avocado", "cantaloupe", "carrot", "cucumber", "potato", "tomato",
    "lettuce", "spinach", "broccoli", "onion", "garlic", "cabbage", "pumpkin", "eggplant", "zucchini", "squash",
    "chicken", "beef", "pork", "turkey", "fish", "salmon", "tuna", "shrimp", "lobster", "crab", 
    "egg", "cheese", "milk", "butter", "cream", "yogurt", "bread", "bagel", "croissant", "pasta",
    "noodle", "rice", "cereal", "oatmeal", "popcorn", "chocolate", "candy", "cookie", "pie", 
    "cake", "cupcake", "brownie", "muffin", "donut", "biscuit", "waffle", "pancake", "syrup",
    "water", "coffee", "tea", "juice", "soda", "beer", "wine", "cocktail", "whiskey", "vodka", 
    "rum", "gin", "champagne", "smoothie", "lemonade", "milkshake", "gingerale", "hotchocolate", "coconutwater",
    "cat", "dog", "horse", "elephant", "giraffe", "tiger", "lion", "bear", "wolf", "fox",
    "rabbit", "deer", "squirrel", "kangaroo", "koala", "panda", "zebra", "monkey", "chimpanzee", "gorilla",
    "leopard", "cheetah", "rhino", "hippopotamus", "crocodile", "alligator", "turtle", "lizard", "snake", "frog",
    "parrot", "eagle", "hawk", "owl", "pigeon", "dove", "penguin", "flamingo", "swan", "duck",
    "robin", "woodpecker", "crow", "seagull", "bat", "beetle", "ant", "bee", "butterfly", "moth",
    "spider", "grasshopper", "dragonfly", "ladybug", "scorpion", "worm", "snail", "shrimp", "lobster", "crab",
    "whale", "dolphin", "shark", "seal", "octopus", "squid", "starfish", "jellyfish", "clam", "coral",
    "beach", "mountain", "forest", "desert", "valley", "river", "ocean", "lake", "waterfall", "canyon",
    "volcano", "island", "hill", "swamp", "marsh", "meadow", "prairie", "rainforest", "tundra", "wetland",
    "city", "town", "village", "suburb", "downtown", "neighborhood", "street", "avenue", "boulevard", "road",
    "bridge", "tunnel", "highway", "intersection", "sidewalk", "square", "park", "plaza", "square", 
    "hotel", "restaurant", "cafe", "bar", "theater", "cinema", "mall", "supermarket", "store", "shop",
    "office", "school", "library", "hospital", "clinic", "church", "temple", "mosque", "stadium", "arena",
    "museum", "gallery", "factory", "warehouse", "market", "gym", "pool", "beach", "zoo",
    "jungle", "farm", "orchard", "greenhouse", "plantation", "meadow", "golfcourse", "playground", "airport",
    "trainstation", "busstop", "subway", "bikepath", "parkinglot", "hospital", "postoffice", "school", "university",
    "library", "farmersmarket", "superstore", "gasstation", "pharmacy", "bank", "ATM", "postoffice", "furniturestore",
    "artgallery", "gym", "furniture", "computerstore", "clothingstore", "bookstore", "sportinggoods", "electronics",
    "toystore", "movie", "concert", "play", "opera", "musical", "performance", "tourism", "travel", "vacation",
    "holiday", "flight", "train", "bus", "car", "bicycle", "motorcycle", "bus", "subway", "electriccar",
    "walking", "camping", "hiking", "fishing", "skiing", "surfing", "snowboarding", "boating", "scubadiving", "kayaking",
    "cooking", "baking", "painting", "drawing", "singing", "dancing", "writing", "photography", "acting", "crafting",
    "gardening", "woodworking", "knitting", "sewing", "pottery", "sculpture", "ceramics", "poetry", "fiction",
    "nonfiction", "journalism", "novel", "poem", "book", "magazine", "newspaper", "comic", "manga", "article",
    "essay", "thesis", "research", "presentation", "conference", "workshop", "seminar", "meetup", "event",
    "show", "audience", "interview", "casting", "audition", "actor", "director", "producer", "scriptwriter",
    "camera", "film", "movie", "television", "show", "season", "episode", "series", "realityshow", "competition",
    "contest", "tournament", "championship", "victory", "defeat", "draw", "score", "team", "athlete", "coach",
    "training", "exercise", "fitness", "workout", "cardio", "strength", "flexibility", "endurance", "yoga", "pilates",
    "meditation", "relaxation", "diet", "nutrition", "health", "wellness", "sleep", "rest", "recovery", "rehab",
    "physiotherapy", "massage", "chiropractic", "alternative", "medicine", "doctor", "nurse", "therapist", "counselor",
    "psychiatrist", "psychologist", "dentist", "optometrist", "pediatrician", "cardiologist", "surgeon", "emergency",
    "anxiety", "depression", "stress", "anger", "happiness", "sadness", "love", "peace", "joy", "grief",
    "anger", "fear", "hope", "dream", "goal", "passion", "purpose", "ambition", "determination", "motivation",
    "success", "failure", "achievement", "confidence", "self-esteem", "self-care", "balance", "focus", "growth",
    "mindset", "resilience", "strength", "courage", "bravery", "compassion", "empathy", "generosity", "kindness", "gratitude",
    "strawberry", "tangerine", "ugli fruit", "vanilla", "watermelon", "xigua", "yellow", "passion", "fruit", "zucchini"
])

def get_random_word():
    word = np.random.choice(words)
    return word

